ServiceTrain<-read.csv("serviceTrainData.csv")
ServiceTest<-read.csv("serviceTestData.csv")
View(ServiceTrain) 
View(ServiceTest)
str(ServiceTrain)
str(ServiceTest)
as.factor(ServiceTrain$Service) # to convert them in to factors
summary(servicetrain)
summary(servicetest)
predictedknn<- knn(train = ServiceTrain[,-6],test = ServiceTest[,-6],cl=ServiceTrain$Service,k=3)
print(predictedknn)
confusionMatrix(table(predictedknn,ServiceTest[,6]))
print(confusionMatrix)
# now pass the test set 
confMatrix=confusionMatrix(table(predictedknn,ServiceTest$Service))
print(confMatrix)